Headline feature
Tchilo/personal-portfolio pull request #1
Opened 2021-06-04 08:45 UTC by Tchilo

added the headline feature 
added the social media icons

2021-06-04 12:12 UTC, Dipeshtwis requested changes
Hi @Tchilo, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Good use of Flexbox.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [ ] Your project design should follow the one of the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) portfolio. I think you are implementing [this template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471). If not please mention in PR description which design you're following.
 - you can check the differences here. (Also make sure to keep the font and color same).

### Your design

![Screenshot from 2021-06-04 17-37-20](https://user-images.githubusercontent.com/22434660/120798946-b38d2680-c55b-11eb-8787-e9023c785724.png)


### Figma design

![Screenshot from 2021-06-04 17-38-17](https://user-images.githubusercontent.com/22434660/120798963-bab43480-c55b-11eb-96f8-fca33f888f4a.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 12:12 UTC, Dipeshtwis commented on index.html
> +<div id="headline-page">
- [ ] Please use background image as per the style and use `background-image` property in css and `img` tag in html for  this. As background image gives you power to write over the image as well.

2021-06-04 15:06 UTC, jubaan requested changes
Hi @Tchilo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 15:06 UTC, jubaan commented on index.html
> +     <h2>Hey There. <br> I'am Taro!</h2>
- [ ] We should wrap our main title in `<h1>`, this helps SEO.

2021-06-04 15:20 UTC, Tchilo commented
can you please kindly help me with this?
We should use a screenshot of our own project and remove the image of the
template.

On Fri, Jun 4, 2021 at 5:06 PM Julio Añoveros ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Tchilo <https://github.com/Tchilo> ,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> only 3 code reviews per project. If you think that the code review was not
> fair, you can request a second opinion using this form
> <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/Tchilo/personal-portfolio/pull/1#discussion_r645636720>
> :
>
> >
>
> -> One paragraph statement about the project.
>
> +> This is the begining of my portfolio using nothing but HTML and CSS
>
>
>
>  ![screenshot](./app_screenshot.png)
>
>
>
>    - We should use a screenshot of our own project and remove the image
>    of the template.
>
> ------------------------------
>
> In index.html
> <https://github.com/Tchilo/personal-portfolio/pull/1#discussion_r645637529>
> :
>
> > @@ -0,0 +1,43 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>My Portfolio</title>
>
> +    <meta name="description" content="My very first portfolio page.">
>
> +    <link rel="stylesheet" href="style.css">
>
> +    <script src="https://kit.fontawesome.com/b7a7cffe76.js" crossorigin="anonymous"></script>
>
> +  </head>
>
> +<body>
>
> +  <header class="container">
>
> +    <h3 class="logo">My Logo</h3>
>
>
>
>    - Lets change the *logo* to a link using an anchor tag <a>
>
> ------------------------------
>
> In index.html
> <https://github.com/Tchilo/personal-portfolio/pull/1#discussion_r645638492>
> :
>
> > +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>My Portfolio</title>
>
> +    <meta name="description" content="My very first portfolio page.">
>
> +    <link rel="stylesheet" href="style.css">
>
> +    <script src="https://kit.fontawesome.com/b7a7cffe76.js" crossorigin="anonymous"></script>
>
> +  </head>
>
> +<body>
>
> +  <header class="container">
>
> +    <h3 class="logo">My Logo</h3>
>
> +    <a href="#"><i class="fa fa-bars"></i></a>
>
> +  </header>
>
> +
>
> +<div id="headline-page">
>
>
>
>    - We should try the previous Code Reviewer request and convert the
>    <div> into <section>
>
> ------------------------------
>
> In index.html
> <https://github.com/Tchilo/personal-portfolio/pull/1#discussion_r645645215>
> :
>
> > +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>My Portfolio</title>
>
> +    <meta name="description" content="My very first portfolio page.">
>
> +    <link rel="stylesheet" href="style.css">
>
> +    <script src="https://kit.fontawesome.com/b7a7cffe76.js" crossorigin="anonymous"></script>
>
> +  </head>
>
> +<body>
>
> +  <header class="container">
>
> +    <h3 class="logo">My Logo</h3>
>
> +    <a href="#"><i class="fa fa-bars"></i></a>
>
> +  </header>
>
> +
>
> +<div id="headline-page">
>
> +   <div class="intro">
>
> +     <h2>Hey There. <br> I'am Taro!</h2>
>
>
>
>    - We should wrap our main title in <h1>, this helps SEO.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Tchilo/personal-portfolio/pull/1#pullrequestreview-676376612>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGFHPPBNIZR2KLZUHMOMQ5LTRDTY3ANCNFSM46CLVG4Q>
> .
>

2021-06-04 20:11 UTC, MahmoudBakr23 requested changes
Hi @Tchilo😃, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
_Check the **OPTIONAL** comments under the review._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 20:11 UTC, MahmoudBakr23 commented on index.html
> +     <h1 class="text-1">I'am a Software Developer</h1>
- [ ] As requested earlier, and according to the Semantic HTML (more details in the comment above), kindly make the subtitle in `<hx>` tag, for example `<h2>` tag since it's not the main headline.

2021-06-04 20:11 UTC, MahmoudBakr23 commented on index.html
> +
- [ ] **OPTIONAL** I recommend removing this blank line here to help to keep your code clean.

_Please keep in mind that blank lines and indentations are only to separate two logic pieces of code or two large sections apart._

2021-06-04 20:11 UTC, MahmoudBakr23 commented on style.css
> +/* left empty */
- [ ] **OPTIONAL** I recommend removing this line because it's unnecessary and points out to nothing, what do you think?

_Please keep in mind that blank lines and indentations are only to separate two logic pieces of code or two large sections apart._

2021-06-05 08:56 UTC, MahmoudBakr23 approved these changes
Hi @Tchilo 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it.
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 09:14 UTC, merged